# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JCVideoPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JCVideoPlayerDemo
  pod 'Masonry'
  target 'JCVideoPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JCVideoPlayerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
